//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace VieKoreaFoods {
    
    
    public partial class _default {
        
        /// <summary>
        /// ucNavigation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VieKoreaFoods.UserControl.ucNavigation ucNavigation;
        
        /// <summary>
        /// ucSlideOrMenu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VieKoreaFoods.UserControl.ucSlideOrMenu ucSlideOrMenu;
        
        /// <summary>
        /// ucProducts control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VieKoreaFoods.UserControl.ucProducts ucProducts;
        
        /// <summary>
        /// ucLogin control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VieKoreaFoods.UserControls.ucLogin ucLogin;
    }
}
